baseURL = "https://shwchurch3.github.io/t5/"
languageCode = "zh-cn"
title = "北京守望教会"
theme = "hugo-theme-yuki"


# Copyright notice. This will display on the footer.
copyright = ""
paginate = 10

# Theme config
[params]

  # The content you want to be listed on list pages.
  mainSections = ["post"]

  # The information will display on the post pages.
  author = "守望"
  description = "守望官网"
  authorwebsite = "https://t5.shwchurch.org/"

  # The path to your images
  favicon = "images/logo.png"
  logo = "images/logo.png"
  avatar = ""
  displayImg = "images/display.png"


# Navbar config
[[menu.nav]]
    name = "HOME"
    url = "/"
    weight = 1

[[menu.nav]]
    name = "BLOG"
    url = "/post"
    weight = 2

[[menu.nav]]
    name = "ABOUT"
    url = "/about"
    weight = 3

[[menu.nav]]
    name = "TAGS"
    url = "/tags/"
    weight = 4

# Social accounts config (This will display on the index page)
[[menu.social]]
    name = "Example-1"
    url = "/"
    weight = 1

[[menu.social]]
    name = "Example-2"
    url = "/"
    weight = 2

[[menu.social]]
    name = "Example-3"
    url = "/"
    weight = 3

